<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.4" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="10.0.10" />
    <PackageReference Include="Microsoft.AspNetCore.TestHost" Version="10.0.10" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\GORT.Api\GORT.Api.csproj" />
    <ProjectReference Include="..\..\src\GORT.Agent\GORT.Agent.csproj" />
    <ProjectReference Include="..\..\src\GORT.ServiceBus\GORT.ServiceBus.csproj" />
    <ProjectReference Include="..\..\src\GORT.Observability\GORT.Observability.csproj" />
    <ProjectReference Include="..\..\src\GORT.Modules\GORT.Modules.csproj" />
    <ProjectReference Include="..\..\src\GORT.Modules.Share\GORT.Modules.Share.csproj" />
    <ProjectReference Include="..\..\src\GORT.Modules.Backup\GORT.Modules.Backup.csproj" />
    <ProjectReference Include="..\..\src\GORT.Modules.Storage\GORT.Modules.Storage.csproj" />
  </ItemGroup>

</Project>