#!/usr/bin/env bash
set -Eeuo pipefail

readonly ARCHITECTURE="amd64"
readonly DOTNET_RUNTIME="linux-x64"
readonly VERSION="${FortOS_VERSION:?FortOS_VERSION must be set by build.sh}"
readonly SAFE_VERSION="${VERSION//[^a-zA-Z0-9._-]/-}"
readonly IMAGE_BASENAME="fortos-debian12-${SAFE_VERSION}-${ARCHITECTURE}"
readonly BUILD_ROOT="/build/fortos-iso"
readonly LIVE_ROOT="${BUILD_ROOT}/live"
readonly PUBLISH_ROOT="${BUILD_ROOT}/publish"
readonly DOTNET_ROOT="/opt/dotnet"

export DEBIAN_FRONTEND=noninteractive
export DOTNET_CLI_TELEMETRY_OPTOUT=1
export DOTNET_NOLOGO=1
export NUGET_PACKAGES="${BUILD_ROOT}/nuget"
export PATH="${DOTNET_ROOT}:${PATH}"

install_builder_dependencies() {
    apt-get -o Acquire::Retries=5 update
    apt-get -o Acquire::Retries=5 install -y --no-install-recommends \
        ca-certificates \
        cpio \
        curl \
        debootstrap \
        dosfstools \
        isolinux \
        libicu72 \
        libssl3 \
        libunwind8 \
        live-build \
        mtools \
        squashfs-tools \
        syslinux-common \
        xorriso
    rm -rf /var/lib/apt/lists/*
}

install_dotnet_sdk() {
    curl --fail --show-error --silent --location \
        --retry 5 \
        --retry-delay 2 \
        --retry-all-errors \
        https://dot.net/v1/dotnet-install.sh \
        --output /tmp/dotnet-install.sh
    chmod 0755 /tmp/dotnet-install.sh
    /tmp/dotnet-install.sh \
        --version "${DOTNET_SDK_VERSION:?DOTNET_SDK_VERSION must be set}" \
        --install-dir "${DOTNET_ROOT}" \
        --no-path
}

publish_fortos() {
    # The FortOS.Dashboard frontend output is generated by the Vite build (not committed to the repo).
    # If it is missing, the target system returns 404 for /dashboard — abort if missing to avoid producing an unusable ISO.
    if [[ ! -f /workspace/src/FortOS.Api/wwwroot/dashboard/index.html ]]; then
        echo "error: /workspace/src/FortOS.Api/wwwroot/dashboard/index.html not found — run the frontend build first:" >&2
        echo "  cd src/FortOS.Dashboard && npm ci && npm run build" >&2
        exit 1
    fi
    mkdir -p "${PUBLISH_ROOT}/api" "${PUBLISH_ROOT}/cli"

    dotnet publish /workspace/src/FortOS.Api/FortOS.Api.csproj \
        --configuration Release \
        --runtime "${DOTNET_RUNTIME}" \
        --self-contained true \
        --artifacts-path "${BUILD_ROOT}/artifacts" \
        --output "${PUBLISH_ROOT}/api"

    dotnet publish /workspace/src/FortOS.Cli/FortOS.Cli.csproj \
        --configuration Release \
        --runtime "${DOTNET_RUNTIME}" \
        --self-contained true \
        --artifacts-path "${BUILD_ROOT}/artifacts" \
        --output "${PUBLISH_ROOT}/cli"
}

# FortOS graphical installer (GUI kiosk + headless CLI, design §8.2).
# --self-contained + partial trimming keep the image delta small (target <= 300 MB, §8.5).
publish_installer() {
    mkdir -p "${PUBLISH_ROOT}/installer/gui" "${PUBLISH_ROOT}/installer/cli"

    dotnet publish /workspace/src/FortOS.Installer.Gui/FortOS.Installer.Gui.csproj \
        --configuration Release \
        --runtime "${DOTNET_RUNTIME}" \
        --self-contained true \
        -p:PublishTrimmed=true -p:TrimMode=partial \
        --artifacts-path "${BUILD_ROOT}/artifacts" \
        --output "${PUBLISH_ROOT}/installer/gui"

    dotnet publish /workspace/src/FortOS.Installer.Cli/FortOS.Installer.Cli.csproj \
        --configuration Release \
        --runtime "${DOTNET_RUNTIME}" \
        --self-contained true \
        -p:PublishTrimmed=true -p:TrimMode=partial \
        --artifacts-path "${BUILD_ROOT}/artifacts" \
        --output "${PUBLISH_ROOT}/installer/cli"
}

configure_live_image() {
    mkdir -p "${LIVE_ROOT}"
    cd "${LIVE_ROOT}"

    # -----------------------------------------------------------------
    # Detect local package cache (pre-built by bootstrap-debian12.sh)
    # When present, the ISO build avoids downloading packages from the
    # internet — all .deb files are resolved from the local cache.
    # -----------------------------------------------------------------
    local CACHE_DEBS="/workspace/fortos debian12/cache/debs"
    local USE_LOCAL_CACHE=false
    if [[ -d "${CACHE_DEBS}" ]] && compgen -G "${CACHE_DEBS}/*.deb" > /dev/null; then
        USE_LOCAL_CACHE=true
        local CACHED_COUNT
        CACHED_COUNT=$(find "${CACHE_DEBS}" -maxdepth 1 -name '*.deb' | wc -l)
        echo "=== Using local Debian package cache (${CACHED_COUNT} .deb files) ==="
    else
        echo "=== No local cache at '${CACHE_DEBS}'. Packages will be downloaded. ==="
        echo "    To create the cache: cd 'fortos debian12' && bash scripts/bootstrap-debian12.sh debs"
    fi

    local live_boot_append="boot=live components hostname=fortos locales=en_US.UTF-8,zh_CN.UTF-8 keyboard-layouts=us console=tty0 console=ttyS0,115200n8 noautologin"

    # LB_BOOTSTRAP_INCLUDE=gnupg: keep gpg/gpgv in the chroot (the gnupg
    # default only applies to ubuntu modes).
    # --apt-secure false: live-build signs the local packages.chroot repository
    # (docker .debs) by generating a key inside the chroot with gpg; with
    # bookworm's gpg 2.2 in a TTY-less build this fails with "agent_genkey
    # failed: Inappropriate ioctl for device". Disabling apt secure skips that
    # signing step (and debootstrap's --no-check-gpg).
    # --firmware-chroot/--firmware-binary false: live-build resolves firmware
    # packages from dists/bookworm/Contents-amd64.gz, which the official
    # mirrors removed after bookworm's end-of-life (404).
    LB_BOOTSTRAP_INCLUDE=gnupg lb config \
        --mode debian \
        --distribution bookworm \
        --architecture "${ARCHITECTURE}" \
        --archive-areas "main contrib non-free-firmware" \
        --security false \
        --apt-secure false \
        --firmware-chroot false \
        --firmware-binary false \
        --binary-image iso-hybrid \
        --checksums sha256 \
        --debian-installer live \
        --debian-installer-distribution bookworm \
        --debian-installer-gui true \
        --bootappend-live "${live_boot_append}" \
        --iso-application "FortOS Debian 12 Installer" \
        --iso-publisher "FortOS Project" \
        --iso-volume "FortOS_${SAFE_VERSION:0:20}" \
        --uefi-secure-boot auto

    cp -a /workspace/eng/iso/config/. "${LIVE_ROOT}/config/"
    # Windows checkouts may expose CRLF files through the read-only bind mount.
    # live-build treats the trailing CR as part of package names and unit values,
    # so normalize the copied configuration before it is consumed.
    find "${LIVE_ROOT}/config" -type f -exec sed -i 's/\r$//' {} +
    find "${LIVE_ROOT}/config/hooks" -type f -name '*.hook.chroot' -exec chmod 0755 {} +

    # Windows checkouts may also materialize git symlinks as regular files
    # (core.symlinks=false). systemd then rejects the pre-created
    # multi-user.target.wants drop-ins ("not a symlink, ignoring") and the
    # installer/GUI services never start. Recreate symlinks from the git
    # index so the squashfs ships real symlinks regardless of checkout OS.
    if git -C /workspace rev-parse --git-dir >/dev/null 2>&1; then
        while read -r mode hash stage rel; do
            if [[ "${mode}" == "120000" && -n "${rel}" ]]; then
                src="${LIVE_ROOT}/config/${rel#eng/iso/config/}"
                if [[ -e "${src}" && ! -L "${src}" ]]; then
                    target="$(cat "${src}" 2>/dev/null || true)"
                    if [[ -n "${target}" && "${target}" != *$'\r'* ]]; then
                        rm -f "${src}"
                        ln -s "${target}" "${src}"
                    fi
                fi
            fi
        done < <(git -C /workspace ls-files -s eng/iso/config/includes.chroot 2>/dev/null || true)
    fi

    # -----------------------------------------------------------------
    # Package staging — use local cache when available. This replaces
    # per-package 'apt-get download' calls with pre-resolved transitive
    # dependency trees stored in the repository.
    # -----------------------------------------------------------------
    mkdir -p "${LIVE_ROOT}/config/packages.chroot"

    if ${USE_LOCAL_CACHE}; then
        # Stage 1: Copy all cached .deb files into packages.chroot.
        # live-build installs these via dpkg during chroot creation.
        # Because the cache contains the full transitive closure, no
        # network access is needed during lb build.
        cp -a "${CACHE_DEBS}"/*.deb "${LIVE_ROOT}/config/packages.chroot/"

        # Stage 2: Mirror cache into the chroot at a known location
        # and register it as a local apt source. This lets apt satisfy
        # any remaining dependency edges without reaching the network.
        mkdir -p "${LIVE_ROOT}/config/includes.chroot/var/cache/fortos-packages"
        cp -a "${CACHE_DEBS}"/*.deb "${LIVE_ROOT}/config/includes.chroot/var/cache/fortos-packages/"
        if [[ -f "${CACHE_DEBS}/Packages.gz" ]]; then
            cp -a "${CACHE_DEBS}/Packages.gz" "${LIVE_ROOT}/config/includes.chroot/var/cache/fortos-packages/"
        fi
        # Register the local repo inside the build chroot so apt picks it up.
        mkdir -p "${LIVE_ROOT}/config/archives"
        cat > "${LIVE_ROOT}/config/archives/fortos-cache.list.chroot" << 'APTEOF'
deb [trusted=yes] file:/var/cache/fortos-packages ./
APTEOF
        echo "Local cache staged: packages.chroot + file:// apt source."

        # Cache may not include Docker packages (from third-party repo).
        # When missing, download them now so the ISO has a complete set.
        if ! ls "${LIVE_ROOT}/config/packages.chroot/containerd.io_*.deb" >/dev/null 2>&1; then
            echo "Docker packages missing from cache — downloading..."
            install -d -m 0755 /etc/apt/keyrings
            curl --fail --show-error --silent --location \
                --retry 5 --retry-delay 2 --retry-all-errors \
                https://download.docker.com/linux/debian/gpg \
                --output /etc/apt/keyrings/docker.asc
            printf '%s\n' \
                "deb [arch=${ARCHITECTURE} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian bookworm stable" \
                > /etc/apt/sources.list.d/docker.list
            apt-get -o Acquire::Retries=5 update
            (
                cd "${LIVE_ROOT}/config/packages.chroot"
                apt-get download \
                    containerd.io \
                    docker-buildx-plugin \
                    docker-ce \
                    docker-ce-cli \
                    docker-compose-plugin
            )
        fi
    fi

    # -----------------------------------------------------------------
    # Docker GPG key and apt source — always provisioned for the
    # installed system so Docker can receive updates post-install.
    # When the cache is active, Docker packages come from cache/debs/
    # (included above) and no separate download step is needed.
    # -----------------------------------------------------------------
    install -d -m 0755 /etc/apt/keyrings
    if [[ -f "${CACHE_DEBS}/../docker-key.asc" ]]; then
        cp "${CACHE_DEBS}/../docker-key.asc" /etc/apt/keyrings/docker.asc
    else
        curl --fail --show-error --silent --location \
            --retry 5 \
            --retry-delay 2 \
            --retry-all-errors \
            https://download.docker.com/linux/debian/gpg \
            --output /etc/apt/keyrings/docker.asc
    fi
    printf '%s\n' \
        "deb [arch=${ARCHITECTURE} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian bookworm stable" \
        > /etc/apt/sources.list.d/docker.list

    mkdir -p "${LIVE_ROOT}/config/includes.chroot/etc/apt/keyrings"
    cp /etc/apt/keyrings/docker.asc \
        "${LIVE_ROOT}/config/includes.chroot/etc/apt/keyrings/docker.asc"

    # Fallback: download Docker packages from network when cache is absent.
    if ! ${USE_LOCAL_CACHE}; then
        apt-get -o Acquire::Retries=5 update
        (
            cd "${LIVE_ROOT}/config/packages.chroot"
            apt-get download \
                containerd.io \
                docker-buildx-plugin \
                docker-ce \
                docker-ce-cli \
                docker-compose-plugin
        )
    fi

    mkdir -p "${LIVE_ROOT}/config/includes.chroot/opt/fortos"
    cp -a "${PUBLISH_ROOT}/api" "${LIVE_ROOT}/config/includes.chroot/opt/fortos/"
    cp -a "${PUBLISH_ROOT}/cli" "${LIVE_ROOT}/config/includes.chroot/opt/fortos/"
    cp -a "${PUBLISH_ROOT}/installer" "${LIVE_ROOT}/config/includes.chroot/opt/fortos/"
    printf '%s\n' "${VERSION}" > "${LIVE_ROOT}/config/includes.chroot/etc/fortos/version"
}

build_image() {
    cd "${LIVE_ROOT}"
    lb build

    local built_image="${LIVE_ROOT}/live-image-${ARCHITECTURE}.hybrid.iso"
    if [[ ! -s "${built_image}" ]]; then
        echo "error: live-build did not produce ${built_image}." >&2
        exit 1
    fi

    install -m 0644 "${built_image}" "/output/${IMAGE_BASENAME}.iso"
    cd /output
    sha256sum "${IMAGE_BASENAME}.iso" > "${IMAGE_BASENAME}.iso.sha256"
    chown "${OUTPUT_UID:?OUTPUT_UID must be set}:${OUTPUT_GID:?OUTPUT_GID must be set}" \
        "${IMAGE_BASENAME}.iso" "${IMAGE_BASENAME}.iso.sha256"
}

install_builder_dependencies
install_dotnet_sdk
publish_fortos
publish_installer
configure_live_image
build_image

echo "Created /output/${IMAGE_BASENAME}.iso"
