#!/usr/bin/env bash
# -------------------------------------------------------------------------
# FortOS Debian ISO - native local build script (runs directly in WSL or any
# Debian-based host; no Docker required; equivalent to the local execution
# path of eng/iso/build-in-container.sh).
#
# Dependencies (dotnet SDK 10 preferred at /opt/dotnet, or in PATH):
#   live-build xorriso squashfs-tools curl apt-get git mtools dosfstools
#
# Usage:
#   bash eng/iso/build-local-wsl.sh
#   VERSION=v1.2.3 OUTPUT_DIR=/path bash eng/iso/build-local-wsl.sh
#
# Notes:
#   - Restores includes.chroot symlinks lost in a Windows checkout from the
#     git index (core.symlinks=false materializes symlinks as regular files,
#     and systemd then rejects the wants drop-in with "not a symlink").
#   - Docker packages are pinned to bookworm versions via apt pin (WSL and
#     other hosts ship newer versions, and apt would otherwise try to resolve
#     a non-existent version).
#   - Writes the ISO and .sha256 to ${OUTPUT_DIR} (default artifacts/iso).
# -------------------------------------------------------------------------
set -Eeuo pipefail

readonly SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
readonly REPOSITORY_ROOT="$(cd -- "${SCRIPT_DIR}/../.." && pwd)"
readonly VERSION="${VERSION:-dev}"
readonly SAFE_VERSION="${VERSION//[^a-zA-Z0-9._-]/-}"
readonly BUILD_ROOT="${BUILD_ROOT:-${REPOSITORY_ROOT}/artifacts/iso-build}"
readonly PUBLISH_ROOT="${BUILD_ROOT}/publish"
readonly LIVE_ROOT="${BUILD_ROOT}/live"
readonly OUTPUT_DIR="${OUTPUT_DIR:-${REPOSITORY_ROOT}/artifacts/iso}"
readonly IMAGE_BASENAME="fortos-debian12-${SAFE_VERSION}-amd64"

export DOTNET_CLI_TELEMETRY_OPTOUT=1
export DOTNET_NOLOGO=1
export DEBIAN_FRONTEND=noninteractive
export NUGET_PACKAGES="${BUILD_ROOT}/nuget"

# --- dotnet SDK (prefer /opt/dotnet, matching build-in-container.sh) ---
if ! command -v dotnet >/dev/null 2>&1 && [[ -x /opt/dotnet/dotnet ]]; then
    export PATH="/opt/dotnet:${PATH}"
fi
if ! command -v dotnet >/dev/null 2>&1; then
    echo "error: dotnet SDK 10 not found — install it or place it at /opt/dotnet." >&2
    exit 1
fi

# --- Tool checks ---
for cmd in lb xorriso mksquashfs curl apt-get git; do
    if ! command -v "${cmd}" >/dev/null 2>&1; then
        echo "error: ${cmd} is required (apt-get install live-build xorriso squashfs-tools ...)." >&2
        exit 1
    fi
done

# --- Clean up chroot mounts left over from an interrupted build (/proc /sys /dev ...) ---
mount 2>/dev/null | grep "${BUILD_ROOT}" | awk '{print $3}' | sort -r \
    | while read -r m; do umount "${m}" 2>/dev/null || umount -l "${m}" 2>/dev/null || true; done || true
sleep 1

# --- The FortOS.Dashboard frontend output is generated by the Vite build (not committed to the repo).
# If it is missing, the target system returns 404 for /dashboard — abort if missing to avoid producing an unusable ISO.
readonly DASHBOARD_INDEX="${REPOSITORY_ROOT}/src/FortOS.Api/wwwroot/dashboard/index.html"
if [[ ! -f "${DASHBOARD_INDEX}" ]]; then
    echo "error: ${DASHBOARD_INDEX} not found — run the frontend build first:" >&2
    echo "  cd src/FortOS.Dashboard && npm ci && npm run build" >&2
    exit 1
fi

echo "=== 1/6 dotnet publish (4 projects, skips existing output) ==="
mkdir -p "${PUBLISH_ROOT}/api" "${PUBLISH_ROOT}/cli" \
    "${PUBLISH_ROOT}/installer/gui" "${PUBLISH_ROOT}/installer/cli"

publish_if_missing() {
    local output="$1" bin="$2" extra="${3:-}"
    shift 3
    if [[ -x "${output}/${bin}" ]]; then
        echo "  ${bin} already exists, skipping"
        return
    fi
    dotnet publish "${REPOSITORY_ROOT}/$1" \
        --configuration Release --runtime linux-x64 --self-contained true \
        ${extra} --output "${output}" >/dev/null
    echo "  ${bin} OK"
}
publish_if_missing "${PUBLISH_ROOT}/api" FortOS.Api "" "src/FortOS.Api/FortOS.Api.csproj"
publish_if_missing "${PUBLISH_ROOT}/cli" FortOS.Cli "" "src/FortOS.Cli/FortOS.Cli.csproj"
publish_if_missing "${PUBLISH_ROOT}/installer/gui" fortos-installer-gui \
    "-p:PublishTrimmed=true -p:TrimMode=partial" "src/FortOS.Installer.Gui/FortOS.Installer.Gui.csproj"
publish_if_missing "${PUBLISH_ROOT}/installer/cli" fortos-installer \
    "-p:PublishTrimmed=true -p:TrimMode=partial" "src/FortOS.Installer.Cli/FortOS.Installer.Cli.csproj"

echo "=== 2/6 lb config ==="
rm -rf "${LIVE_ROOT}"
mkdir -p "${LIVE_ROOT}"
cd "${LIVE_ROOT}"
# --uefi-secure-boot (signed shim + grub-efi) was added in live-build
# 1:20170829; Debian bookworm ships 1:20230502 (supported), but Ubuntu 24.04's
# live-build fork (3.0~a57-1ubuntu49) rejects the option. Probe the installed
# live-build so the same script works on both hosts.
secure_boot_args=()
if lb config --help 2>/dev/null | grep -q -- '--uefi-secure-boot'; then
    secure_boot_args=(--uefi-secure-boot auto)
else
    echo "  note: live-build lacks --uefi-secure-boot; building without Secure Boot shim" >&2
fi
lb config \
    --mode debian \
    --distribution bookworm \
    --architecture amd64 \
    --archive-areas "main contrib non-free-firmware" \
    --binary-image iso-hybrid \
    --checksums sha256 \
    --debian-installer live \
    --debian-installer-distribution bookworm \
    --debian-installer-gui true \
    --bootappend-live "boot=live components hostname=fortos locales=en_US.UTF-8,zh_CN.UTF-8 keyboard-layouts=us console=tty0 console=ttyS0,115200n8 noautologin" \
    --iso-application "FortOS Debian 12 Installer" \
    --iso-publisher "FortOS Project" \
    --iso-volume "FortOS_${SAFE_VERSION:0:20}" \
    "${secure_boot_args[@]}"

echo "=== 3/6 Copy config + CRLF normalization + symlink restore ==="
cp -a "${REPOSITORY_ROOT}/eng/iso/config/." "${LIVE_ROOT}/config/"
find "${LIVE_ROOT}/config" -type f -exec sed -i 's/\r$//' {} +
find "${LIVE_ROOT}/config/hooks" -type f -name '*.hook.chroot' -exec chmod 0755 {} +
# Restore git symlinks (includes.chroot) materialized as regular files by a
# Windows checkout
while read -r mode hash stage rel; do
    if [[ "${mode}" == "120000" && -n "${rel}" ]]; then
        src="${LIVE_ROOT}/config/${rel#eng/iso/config/}"
        if [[ -e "${src}" && ! -L "${src}" ]]; then
            target="$(cat "${src}" 2>/dev/null || true)"
            if [[ -n "${target}" && "${target}" != *$'\r'* ]]; then
                rm -f "${src}"
                ln -s "${target}" "${src}"
            fi
        fi
    fi
done < <(git -C "${REPOSITORY_ROOT}" ls-files -s eng/iso/config/includes.chroot 2>/dev/null || true)

echo "=== 4/6 Copy FortOS artifacts into includes.chroot ==="
mkdir -p "${LIVE_ROOT}/config/packages.chroot"
mkdir -p "${LIVE_ROOT}/config/includes.chroot/opt/fortos"
cp -a "${PUBLISH_ROOT}/api" "${LIVE_ROOT}/config/includes.chroot/opt/fortos/"
cp -a "${PUBLISH_ROOT}/cli" "${LIVE_ROOT}/config/includes.chroot/opt/fortos/"
cp -a "${PUBLISH_ROOT}/installer" "${LIVE_ROOT}/config/includes.chroot/opt/fortos/"
printf '%s\n' "${VERSION}" > "${LIVE_ROOT}/config/includes.chroot/etc/fortos/version"

echo "=== 5/6 Docker packages (apt pin forces bookworm versions) ==="
install -d -m 0755 /etc/apt/keyrings
curl --fail --show-error --silent --location --retry 3 \
    https://download.docker.com/linux/debian/gpg \
    --output /etc/apt/keyrings/docker.asc
printf '%s\n' \
    "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian bookworm stable" \
    > /etc/apt/sources.list.d/docker.list
cat > /etc/apt/preferences.d/fortos-docker-pin <<'PINEOF'
Package: containerd.io docker-ce docker-ce-cli docker-buildx-plugin docker-compose-plugin
Pin: origin download.docker.com
Pin-Priority: 1001
PINEOF
apt-get -o Acquire::Retries=3 update >/dev/null 2>&1 || true
(
    cd "${LIVE_ROOT}/config/packages.chroot"
    apt-get download containerd.io docker-buildx-plugin docker-ce docker-ce-cli docker-compose-plugin >/dev/null 2>&1
)
mkdir -p "${LIVE_ROOT}/config/includes.chroot/etc/apt/keyrings"
cp /etc/apt/keyrings/docker.asc "${LIVE_ROOT}/config/includes.chroot/etc/apt/keyrings/docker.asc"
echo "  Docker packages: $(ls "${LIVE_ROOT}"/config/packages.chroot/*.deb 2>/dev/null | wc -l) debs"

echo "=== 6/6 lb build (full FortOS ISO) ==="
cd "${LIVE_ROOT}"
lb build

echo "=== Output ISO ==="
mkdir -p "${OUTPUT_DIR}"
cp "${LIVE_ROOT}/live-image-amd64.hybrid.iso" "${OUTPUT_DIR}/${IMAGE_BASENAME}.iso"
(cd "${OUTPUT_DIR}" && sha256sum "${IMAGE_BASENAME}.iso" > "${IMAGE_BASENAME}.iso.sha256")
ls -la "${OUTPUT_DIR}/${IMAGE_BASENAME}.iso"
echo "=== Done: ${OUTPUT_DIR}/${IMAGE_BASENAME}.iso ==="
