using FortOS.Installer.Core.Models;

namespace FortOS.Installer.Core.Steps;

/// <summary>
/// Install context shared between steps: target disk, partition devices, UUIDs,
/// boot mode, and summary. Initialized by the session during the CollectInfo
/// phase and filled in sequentially by each step.
/// </summary>
public sealed class InstallContext
{
    /// <summary>User configuration.</summary>
    public required InstallConfig Config { get; init; }

    /// <summary>Target rootfs mount point.</summary>
    public string TargetMount { get; init; } = "/target";

    /// <summary>Copy source (live rootfs or squashfs mount point).</summary>
    public string SourcePath { get; init; } = "/";

    /// <summary>Actual boot mode (detected by PartitionStep, used by Format/Bootloader).</summary>
    public BootModeKind? BootMode { get; set; }

    /// <summary>System disk partition number → device path (e.g. 2 → /dev/sda2).</summary>
    public Dictionary<int, string> SystemPartitionDevices { get; } = [];

    /// <summary>System disk partition specs (generated by PartitionStep, used by FormatStep).</summary>
    public List<PartitionSpec> SystemPartitions { get; } = [];

    /// <summary>Data disk device (single disk partition / RAID device / LUKS mapper).</summary>
    public string? DataDevice { get; set; }

    /// <summary>Data disk source device (the disk holding the LUKS container, used to read the container UUID for crypttab).</summary>
    public string? DataSourceDevice { get; set; }

    /// <summary>Role → UUID: <c>root</c>/<c>efi</c>/<c>swap</c>/<c>data</c>.</summary>
    public Dictionary<string, string> Uuids { get; } = [];

    /// <summary>Install summary (filled in progressively).</summary>
    public InstallSummary Summary { get; } = new();
}
