<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\FortOS.Core\FortOS.Core.csproj" />
    <ProjectReference Include="..\FortOS.Security\FortOS.Security.csproj" />
    <ProjectReference Include="..\FortOS.ServiceBus\FortOS.ServiceBus.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Docker.DotNet" Version="3.125.15" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.10" />
    <PackageReference Include="Scriban" Version="7.2.5" />
    <PackageReference Include="YamlDotNet" Version="18.1.0" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
