using FortOS.Installer.Core.Exceptions;
using FortOS.Installer.Core.Steps;

namespace FortOS.Tests.Installer.Steps;

public class BootloaderStepTests
{
    private const string ValidGrubCfg = """
        #
        # DO NOT EDIT THIS FILE
        #
        # It is automatically generated by grub-mkconfig using templates
        # from /etc/grub.d and settings from /etc/default/grub
        #

        ### BEGIN /etc/grub.d/00_header ###
        if [ -s $prefix/grubenv ]; then
          load_env
        fi
        ### END /etc/grub.d/00_header ###

        ### BEGIN /etc/grub.d/10_linux ###
        menuentry 'FortOS (Debian GNU/Linux)' --class debian --class gnu-linux --class gnu --class os $menuentry_id_option 'gnulinux-simple-uuid' {
        	load_video
        	insmod gzio
        	insmod part_gpt
        	insmod ext2
        	search --no-floppy --fs-uuid --set=root root-uuid
        	linux	/boot/vmlinuz-6.1.0-52-amd64 root=UUID=root-uuid ro quiet
        	initrd	/boot/initrd.img-6.1.0-52-amd64
        }
        ### END /etc/grub.d/10_linux ###
        """;

    [Fact]
    public void ValidateGrubConfig_ValidConfig_Passes()
    {
        BootloaderStep.ValidateGrubConfig(ValidGrubCfg);
    }

    [Theory]
    [InlineData("")]
    [InlineData("   ")]
    [InlineData("\n\n")]
    public void ValidateGrubConfig_EmptyOrWhitespace_Throws(string config)
    {
        var ex = Assert.Throws<StepException>(() => BootloaderStep.ValidateGrubConfig(config));
        Assert.Contains("empty grub.cfg", ex.Message);
    }

    [Fact]
    public void ValidateGrubConfig_NoMenuentry_Throws()
    {
        var cfg = """
            # only headers, no boot entries
            if [ -s $prefix/grubenv ]; then
              load_env
            fi
            """;
        var ex = Assert.Throws<StepException>(() => BootloaderStep.ValidateGrubConfig(cfg));
        Assert.Contains("no menuentry", ex.Message);
    }

    [Fact]
    public void ValidateGrubConfig_NoLinuxLine_Throws()
    {
        var cfg = ValidGrubCfg.Replace(
            "linux\t/boot/vmlinuz-6.1.0-52-amd64 root=UUID=root-uuid ro quiet",
            "# linux line removed");
        var ex = Assert.Throws<StepException>(() => BootloaderStep.ValidateGrubConfig(cfg));
        Assert.Contains("no linux kernel lines", ex.Message);
    }

    [Fact]
    public void ValidateGrubConfig_LinuxLineWithoutRoot_Throws()
    {
        var cfg = ValidGrubCfg.Replace(
            "root=UUID=root-uuid ro quiet",
            "ro quiet");
        var ex = Assert.Throws<StepException>(() => BootloaderStep.ValidateGrubConfig(cfg));
        Assert.Contains("lacks the root= parameter", ex.Message);
    }

    [Fact]
    public void ValidateGrubConfig_NoInitrdLine_Throws()
    {
        var cfg = ValidGrubCfg.Replace(
            "initrd\t/boot/initrd.img-6.1.0-52-amd64",
            "# initrd line missing");
        var ex = Assert.Throws<StepException>(() => BootloaderStep.ValidateGrubConfig(cfg));
        Assert.Contains("no initrd line", ex.Message);
    }

    [Fact]
    public void ValidateGrubConfig_DeviceRootParameter_Accepts()
    {
        // GRUB_DISABLE_LINUX_UUID=true 时 grub-mkconfig 用 root=/dev/sdaX 而非 UUID,
        // 同样合法,校验不应误杀。
        var cfg = ValidGrubCfg.Replace("root=UUID=root-uuid", "root=/dev/sda3");
        BootloaderStep.ValidateGrubConfig(cfg);
    }

    [Fact]
    public void ValidateGrubConfig_MemtestAndLinuxefiVariants_DoNotConfuse()
    {
        // memtest86+ 的 linux16 行不含 vmlinuz,不参与内核行统计;linuxefi 变体
        // (UEFI 下部分 grub 配置)应被识别为内核行。两者共存不应干扰校验。
        var cfg = ValidGrubCfg
            .Replace("linux\t/boot/vmlinuz", "linuxefi\t/boot/vmlinuz")
            .Replace("initrd\t/boot/initrd.img", "initrdefi\t/boot/initrd.img")
            + """
            menuentry 'Memory test (memtest86+)' {
            	linux16	/boot/memtest86+.bin
            }
            """;
        BootloaderStep.ValidateGrubConfig(cfg);
    }

    [Fact]
    public void ValidateGrubConfig_MemtestOnly_ThrowsForMissingKernel()
    {
        // 只有 memtest 行而无内核条目:报"无内核行"而非误导性的"缺 root="。
        var cfg = """
            menuentry 'Memory test (memtest86+)' {
            	linux16	/boot/memtest86+.bin
            }
            """;
        var ex = Assert.Throws<StepException>(() => BootloaderStep.ValidateGrubConfig(cfg));
        Assert.Contains("no linux kernel lines", ex.Message);
    }

    [Fact]
    public void ValidateGrubConfig_OneKernelLineMissingRoot_Throws()
    {
        // 多个内核条目中只要有一条缺 root= 就必须失败(逐条校验)。
        var recoveryWithoutRoot = """
            menuentry 'FortOS, with Linux 6.1.0-52-amd64 (recovery mode)' {
            	linux	/boot/vmlinuz-6.1.0-52-amd64 ro single
            	initrd	/boot/initrd.img-6.1.0-52-amd64
            }
            """;
        var ex = Assert.Throws<StepException>(
            () => BootloaderStep.ValidateGrubConfig(ValidGrubCfg + "\n" + recoveryWithoutRoot));
        Assert.Contains("lacks the root= parameter", ex.Message);
    }

    [Fact]
    public void ValidateGrubConfig_RecoveryAndAdvancedEntries_Accept()
    {
        // grub-mkconfig 会生成多个 menuentry(高级选项子菜单 + recovery),
        // 每个都应有 initrd 行;校验只要求整体具备可启动要素。
        var recovery = """
            submenu 'Advanced options for FortOS' $menuentry_id_option 'gnulinux-advanced-uuid' {
            	menuentry 'FortOS, with Linux 6.1.0-52-amd64' $menuentry_id_option 'gnulinux-uuid' {
            		linux	/boot/vmlinuz-6.1.0-52-amd64 root=UUID=root-uuid ro quiet
            		initrd	/boot/initrd.img-6.1.0-52-amd64
            	}
            	menuentry 'FortOS, with Linux 6.1.0-52-amd64 (recovery mode)' $menuentry_id_option 'gnulinux-uuid-recovery' {
            		linux	/boot/vmlinuz-6.1.0-52-amd64 root=UUID=root-uuid ro single
            		initrd	/boot/initrd.img-6.1.0-52-amd64
            	}
            }
            """;
        BootloaderStep.ValidateGrubConfig(ValidGrubCfg + "\n" + recovery);
    }
}
