using System.CommandLine;
using System.Globalization;

namespace GORT.Cli.Commands;

/// <summary>Register agent commands.</summary>
public static class AgentCommand
{
    /// <summary>Create agent command.</summary>
    public static Command Create(CliOptions options)
    {
        var root = new Command("agent", "Agent management");
        var list = new Command("list", "List agents");
        list.SetAction((p, ct) => CommandRuntime.RunAsync(p, options, (c, t) => c.GetAsync("api/agents", t), cancellationToken: ct));
        var catalog = BuildCatalogCommand(options);
        var deploy = BuildDeployCommand(options);
        root.Add(list); root.Add(deploy); root.Add(catalog);
        foreach (var verb in new[] { "start", "stop" })
        {
            var id = new Argument<string>("id"); var cmd = new Command(verb, $"{verb} agent") { id };
            cmd.SetAction((p, ct) => CommandRuntime.RunAsync(p, options, (c, t) => c.PostAsync($"api/agents/{Uri.EscapeDataString(p.GetRequiredValue(id))}/{verb}", null, t), cancellationToken: ct));
            root.Add(cmd);
        }
        var logId = new Argument<string>("id"); var follow = new Option<bool>("--follow");
        var logs = new Command("logs", "View agent logs") { logId, follow };
        logs.SetAction(async (p, ct) =>
        {
            if (!p.GetValue(follow)) return await CommandRuntime.RunAsync(p, options, (c, t) => c.GetAsync($"api/agents/{Uri.EscapeDataString(p.GetRequiredValue(logId))}/logs", t), cancellationToken: ct);
            try { using var c = CommandRuntime.Client(p, options); await foreach (var line in c.GetSseStreamAsync($"api/agents/{Uri.EscapeDataString(p.GetRequiredValue(logId))}/logs", ct)) Console.WriteLine(line); return 0; }
            catch (Exception ex) { Console.Error.WriteLine(ex.Message); return 1; }
        });
        var removeId = new Argument<string>("id"); var confirm = new Option<bool>("--confirm");
        var remove = new Command("remove", "Remove agent") { removeId, confirm };
        remove.SetAction((p, ct) => CommandRuntime.RequireConfirm(p.GetValue(confirm)) ? CommandRuntime.RunAsync(p, options, (c, t) => c.DeleteAsync($"api/agents/{Uri.EscapeDataString(p.GetRequiredValue(removeId))}", t), cancellationToken: ct) : Task.FromResult(2));
        root.Add(logs); root.Add(remove);
        return root;
    }

    private static Command BuildCatalogCommand(CliOptions options)
    {
        var catalog = new Command("catalog", "Template catalog management");
        catalog.SetAction((p, ct) => CommandRuntime.RunAsync(p, options, (c, t) => c.GetAsync("api/agents/catalog", t), cancellationToken: ct));

        var list = new Command("list", "List templates");
        list.SetAction((p, ct) => CommandRuntime.RunAsync(p, options, (c, t) => c.GetAsync("api/agents/catalog", t), cancellationToken: ct));

        var searchQuery = new Argument<string>("query");
        var search = new Command("search", "Search templates") { searchQuery };
        search.SetAction((p, ct) => CommandRuntime.RunAsync(p, options, (c, t) => c.GetAsync("api/agents/catalog/search?query=" + Uri.EscapeDataString(p.GetRequiredValue(searchQuery)), t), cancellationToken: ct));

        var installSource = new Argument<string>("source");
        var install = new Command("install", "Install template (local path or URL)") { installSource };
        install.SetAction((p, ct) => CommandRuntime.RunAsync(p, options, (c, t) => c.PostAsync("api/agents/catalog/install", new { source = p.GetRequiredValue(installSource) }, t), cancellationToken: ct));

        var updateTemplate = new Argument<string>("template");
        var update = new Command("update", "Update template") { updateTemplate };
        update.SetAction((p, ct) => CommandRuntime.RunAsync(p, options, (c, t) => c.PostAsync($"api/agents/catalog/{Uri.EscapeDataString(p.GetRequiredValue(updateTemplate))}/update", null, t), cancellationToken: ct));

        catalog.Add(list);
        catalog.Add(search);
        catalog.Add(install);
        catalog.Add(update);
        return catalog;
    }

    private static Command BuildDeployCommand(CliOptions options)
    {
        var template = new Argument<string>("template");
        var agentId = new Option<string>("--agent-id") { Description = "Agent ID (auto-generated by default)" };
        var displayName = new Option<string?>("--display-name") { Description = "Display name (defaults to agent-id)" };
        var image = new Option<string>("--image") { Description = "Container image, e.g. nginx:alpine" };
        var cap = new Option<string[]>("--cap") { Arity = ArgumentArity.ZeroOrMore, Description = "Capabilities, repeatable" };
        var volume = new Option<string[]>("--volume") { Arity = ArgumentArity.ZeroOrMore, Description = "Volume mapping host:container[:ro|rw], repeatable" };
        var port = new Option<string[]>("--port") { Arity = ArgumentArity.ZeroOrMore, Description = "Port mapping host:container[/tcp|udp], repeatable" };
        var cpu = new Option<double?>("--cpu") { Description = "CPU limit, e.g. 1.5" };
        var memoryMiB = new Option<long?>("--memory-mib") { Description = "Memory limit (MiB)" };
        var param = new Option<string[]>("--param") { Arity = ArgumentArity.ZeroOrMore, AllowMultipleArgumentsPerToken = false, Description = "Compatibility parameter k=v, repeatable" };
        var deploy = new Command("deploy", "Deploy agent")
        {
            template,
            agentId,
            displayName,
            image,
            cap,
            volume,
            port,
            cpu,
            memoryMiB,
            param
        };
        deploy.SetAction((p, ct) => CommandRuntime.RunAsync(p, options, (c, t) =>
        {
            var pairs = CommandRuntime.ParsePairs(p.GetValue(param));
            var resolvedTemplate = p.GetRequiredValue(template);
            var resolvedAgentId = p.GetValue(agentId)
                ?? Read(pairs, "agentId", "agent-id", "id")
                ?? "agent-" + Guid.CreateVersion7().ToString("N")[..8];
            var resolvedImage = p.GetValue(image)
                ?? Read(pairs, "image", "imageName", "image-name")
                ?? throw new ArgumentException("Deploying an agent requires --image or --param image=...");
            var resolvedDisplay = p.GetValue(displayName)
                ?? Read(pairs, "displayName", "display-name", "name")
                ?? resolvedAgentId;
            var caps = p.GetValue(cap) is { Length: > 0 } explicitCaps
                ? explicitCaps
                : SplitCsv(Read(pairs, "capabilities", "caps"));
            var volumes = p.GetValue(volume) is { Length: > 0 } explicitVolumes
                ? explicitVolumes.Select(ParseVolume).ToArray()
                : SplitCsv(Read(pairs, "volumes", "volume")).Select(ParseVolume).ToArray();
            var ports = p.GetValue(port) is { Length: > 0 } explicitPorts
                ? explicitPorts.Select(ParsePort).ToArray()
                : SplitCsv(Read(pairs, "ports", "port")).Select(ParsePort).ToArray();
            long? memoryLimitBytes = p.GetValue(memoryMiB) is { } mib ? mib * 1024 * 1024 : null;
            var quota = p.GetValue(cpu) is null && p.GetValue(memoryMiB) is null
                ? null
                : new
                {
                    cpuLimit = p.GetValue(cpu),
                    memoryLimitBytes,
                };
            return c.PostAsync("api/agents/deploy", new
            {
                templateId = resolvedTemplate,
                config = new
                {
                    agentId = resolvedAgentId,
                    displayName = resolvedDisplay,
                    imageName = resolvedImage,
                    capabilities = caps,
                    volumeMapping = volumes,
                    portMapping = ports,
                    resourceQuota = quota,
                }
            }, t);
        }, cancellationToken: ct));
        return deploy;
    }

    private static string? Read(IReadOnlyDictionary<string, string> values, params string[] keys)
    {
        foreach (var key in keys)
        {
            if (values.TryGetValue(key, out var value) && !string.IsNullOrWhiteSpace(value))
            {
                return value.Trim();
            }
        }

        return null;
    }

    private static string[] SplitCsv(string? value)
        => string.IsNullOrWhiteSpace(value)
            ? []
            : value.Split(',', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries);

    private static object ParseVolume(string value)
    {
        var parts = value.Split(':', StringSplitOptions.TrimEntries);
        if (parts.Length < 2 || parts.Length > 3)
        {
            throw new ArgumentException("Volume mapping format should be host:container[:ro|rw].", nameof(value));
        }

        return new
        {
            hostPath = parts[0],
            containerPath = parts[1],
            readOnly = parts.Length == 3 && string.Equals(parts[2], "ro", StringComparison.OrdinalIgnoreCase),
        };
    }

    private static object ParsePort(string value)
    {
        var protocol = "tcp";
        var pair = value;
        var slashIndex = value.IndexOf('/', StringComparison.Ordinal);
        if (slashIndex >= 0)
        {
            protocol = value[(slashIndex + 1)..];
            pair = value[..slashIndex];
        }

        var parts = pair.Split(':', StringSplitOptions.TrimEntries);
        if (parts.Length != 2
            || !int.TryParse(parts[0], NumberStyles.None, CultureInfo.InvariantCulture, out var hostPort)
            || !int.TryParse(parts[1], NumberStyles.None, CultureInfo.InvariantCulture, out var containerPort))
        {
            throw new ArgumentException("Port mapping format should be host:container[/tcp|udp].", nameof(value));
        }

        return new
        {
            hostPort,
            containerPort,
            protocol,
        };
    }
}
